POST http://127.0.0.1:8000/api/register/
Content-Type: application/json

{ "username": "imran", "first_name": "imran", "last_name": "khan", "password": "phitron1234", "email": "imran@gmail.com" }

###

POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{ "email": "imran@gmail.com", "password": "phitron1234" }

###

POST http://127.0.0.1:8000/api/logout/
Content-Type: application/json
Authorization: token ad766fff47b419920aa9c6227c5ee79c0549f51f

###

