# Generated by Django 5.1 on 2024-10-03 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('availability', models.BooleanField(default=True)),
                ('ingredients', models.JSONField()),
                ('image_url', models.URLField(max_length=500)),
                ('ratings', models.DecimalField(decimal_places=2, max_digits=3)),
                ('tags', models.JSONField()),
                ('dietary_info', models.JSONField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='category.category')),
                ('restaurants', models.ManyToManyField(related_name='food_items', to='restaurant.restaurant')),
            ],
        ),
    ]
