# Generated by Django 5.1 on 2024-10-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodItem', '0002_alter_fooditem_restaurants'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='ratings',
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='restaurants',
            field=models.ManyToManyField(related_name='food_items', to='restaurant.restaurant'),
        ),
    ]
