# Generated by Django 5.1 on 2024-10-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodItem', '0003_remove_fooditem_ratings_alter_fooditem_restaurants'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='restaurants',
            field=models.ManyToManyField(blank=True, related_name='food_items', to='restaurant.restaurant'),
        ),
    ]
